# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telegui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Telegui(object):
    def setupUi(self, Telegui):
        Telegui.setObjectName("Telegui")
        Telegui.resize(1033, 833)
        self.AudioBox = QtWidgets.QGroupBox(Telegui)
        self.AudioBox.setGeometry(QtCore.QRect(840, 100, 181, 351))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.AudioBox.setFont(font)
        self.AudioBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.AudioBox.setStyleSheet("")
        self.AudioBox.setObjectName("AudioBox")
        self.MicSlider = QtWidgets.QSlider(self.AudioBox)
        self.MicSlider.setGeometry(QtCore.QRect(50, 80, 16, 231))
        self.MicSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MicSlider.setMinimum(20)
        self.MicSlider.setMaximum(120)
        self.MicSlider.setOrientation(QtCore.Qt.Vertical)
        self.MicSlider.setObjectName("MicSlider")
        self.HeadsetSlider = QtWidgets.QSlider(self.AudioBox)
        self.HeadsetSlider.setGeometry(QtCore.QRect(100, 80, 16, 231))
        self.HeadsetSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.HeadsetSlider.setOrientation(QtCore.Qt.Vertical)
        self.HeadsetSlider.setObjectName("HeadsetSlider")
        self.MicLabel = QtWidgets.QLabel(self.AudioBox)
        self.MicLabel.setGeometry(QtCore.QRect(50, 320, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.MicLabel.setFont(font)
        self.MicLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MicLabel.setObjectName("MicLabel")
        self.HeadsetLabel = QtWidgets.QLabel(self.AudioBox)
        self.HeadsetLabel.setGeometry(QtCore.QRect(100, 320, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.HeadsetLabel.setFont(font)
        self.HeadsetLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.HeadsetLabel.setObjectName("HeadsetLabel")
        self.MicCheck = QtWidgets.QCheckBox(self.AudioBox)
        self.MicCheck.setGeometry(QtCore.QRect(50, 50, 16, 21))
        self.MicCheck.setMouseTracking(True)
        self.MicCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MicCheck.setText("")
        self.MicCheck.setChecked(False)
        self.MicCheck.setTristate(False)
        self.MicCheck.setObjectName("MicCheck")
        self.HeadsetCheck = QtWidgets.QCheckBox(self.AudioBox)
        self.HeadsetCheck.setGeometry(QtCore.QRect(100, 50, 16, 21))
        self.HeadsetCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.HeadsetCheck.setText("")
        self.HeadsetCheck.setObjectName("HeadsetCheck")
        self.MicSlider.raise_()
        self.HeadsetSlider.raise_()
        self.MicLabel.raise_()
        self.HeadsetLabel.raise_()
        self.MicCheck.raise_()
        self.HeadsetCheck.raise_()
        self.VideoBox = QtWidgets.QGroupBox(Telegui)
        self.VideoBox.setGeometry(QtCore.QRect(10, 10, 821, 651))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.VideoBox.setFont(font)
        self.VideoBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.VideoBox.setStyleSheet("")
        self.VideoBox.setObjectName("VideoBox")
        self.Video = QtWidgets.QLabel(self.VideoBox)
        self.Video.setGeometry(QtCore.QRect(10, 40, 800, 600))
        self.Video.setMinimumSize(QtCore.QSize(320, 240))
        self.Video.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Video.setFont(font)
        self.Video.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Video.setStyleSheet("")
        self.Video.setAlignment(QtCore.Qt.AlignCenter)
        self.Video.setObjectName("Video")
        self.ControlBox = QtWidgets.QGroupBox(Telegui)
        self.ControlBox.setGeometry(QtCore.QRect(840, 460, 181, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ControlBox.setFont(font)
        self.ControlBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ControlBox.setStyleSheet("")
        self.ControlBox.setObjectName("ControlBox")
        self.UpButton = QtWidgets.QPushButton(self.ControlBox)
        self.UpButton.setGeometry(QtCore.QRect(70, 40, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.UpButton.setFont(font)
        self.UpButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.UpButton.setStyleSheet("")
        self.UpButton.setObjectName("UpButton")
        self.LeftButton = QtWidgets.QPushButton(self.ControlBox)
        self.LeftButton.setGeometry(QtCore.QRect(20, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LeftButton.setFont(font)
        self.LeftButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LeftButton.setStyleSheet("")
        self.LeftButton.setObjectName("LeftButton")
        self.RightButton = QtWidgets.QPushButton(self.ControlBox)
        self.RightButton.setGeometry(QtCore.QRect(120, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.RightButton.setFont(font)
        self.RightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.RightButton.setStyleSheet("")
        self.RightButton.setObjectName("RightButton")
        self.DownButton = QtWidgets.QPushButton(self.ControlBox)
        self.DownButton.setGeometry(QtCore.QRect(70, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DownButton.setFont(font)
        self.DownButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DownButton.setStyleSheet("")
        self.DownButton.setObjectName("DownButton")
        self.StopButton = QtWidgets.QPushButton(self.ControlBox)
        self.StopButton.setGeometry(QtCore.QRect(20, 140, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.StopButton.setFont(font)
        self.StopButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.StopButton.setStyleSheet("")
        self.StopButton.setObjectName("StopButton")
        self.LogBrowser = QtWidgets.QTextBrowser(Telegui)
        self.LogBrowser.setGeometry(QtCore.QRect(10, 670, 821, 151))
        self.LogBrowser.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LogBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.LogBrowser.setObjectName("LogBrowser")
        self.LaunchButton = QtWidgets.QPushButton(Telegui)
        self.LaunchButton.setGeometry(QtCore.QRect(840, 670, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.LaunchButton.setFont(font)
        self.LaunchButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LaunchButton.setObjectName("LaunchButton")
        self.ConfigButton = QtWidgets.QPushButton(Telegui)
        self.ConfigButton.setGeometry(QtCore.QRect(840, 750, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ConfigButton.setFont(font)
        self.ConfigButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ConfigButton.setObjectName("ConfigButton")
        self.BatteryBox = QtWidgets.QGroupBox(Telegui)
        self.BatteryBox.setGeometry(QtCore.QRect(840, 10, 181, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BatteryBox.setFont(font)
        self.BatteryBox.setObjectName("BatteryBox")
        self.BatteryBar = QtWidgets.QProgressBar(self.BatteryBox)
        self.BatteryBar.setGeometry(QtCore.QRect(10, 40, 162, 23))
        self.BatteryBar.setProperty("value", 100)
        self.BatteryBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.BatteryBar.setObjectName("BatteryBar")

        self.retranslateUi(Telegui)
        QtCore.QMetaObject.connectSlotsByName(Telegui)

    def retranslateUi(self, Telegui):
        _translate = QtCore.QCoreApplication.translate
        Telegui.setWindowTitle(_translate("Telegui", "Телеприсутствие"))
        self.AudioBox.setTitle(_translate("Telegui", "Аудио"))
        self.MicLabel.setText(_translate("Telegui", "Mик."))
        self.HeadsetLabel.setText(_translate("Telegui", "Дин."))
        self.VideoBox.setTitle(_translate("Telegui", "Видео"))
        self.Video.setText(_translate("Telegui", "Видео отсутствует"))
        self.ControlBox.setTitle(_translate("Telegui", "Управление"))
        self.UpButton.setText(_translate("Telegui", "W"))
        self.LeftButton.setText(_translate("Telegui", "A"))
        self.RightButton.setText(_translate("Telegui", "D"))
        self.DownButton.setText(_translate("Telegui", "S"))
        self.StopButton.setText(_translate("Telegui", "SPACE"))
        self.LaunchButton.setText(_translate("Telegui", "Запустить"))
        self.ConfigButton.setText(_translate("Telegui", "Настройки"))
        self.BatteryBox.setTitle(_translate("Telegui", "Аккумулятор"))
        self.BatteryBar.setFormat(_translate("Telegui", "%p%"))

